blog/urls.py
from django.urls import path
from .views import render_posts, post_detail

app_name = "blog"
 
urlpatterns = [ 
    path('', render_posts, name='posts'),
    path("<int:post_id>", post_detail, 
         name="post_detail")
]

django_portfolio/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home ,name='home'),
    path('blog/',include('blog.urls'))
]
urlpatterns += static(settings.MEDIA_URL, 
                      document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
from cloudinary.models import CloudinaryField
class Post(models.Model):
    title=models.CharField(max_length=100)
    description = models.TextField()
    image = CloudinaryField('image')
    date =models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField,URLField
from cloudinary.models import CloudinaryField

class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = CloudinaryField('image')
    url =URLField(blank=True)

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post
def render_posts(request):
    articulos = Post.objects.all()
    return render(request ,'posts.html',
                  {'posts':articulos})

def post_detail(request,post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request,'post_detail.html',{"post":post})

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.
def home(request):
    projects=Project.objects.all()
    return render(request ,'home.html'
                  ,{'projects':projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% block content %}
<h1> Post</h1>
<h2>{{ post.title }}</h2>
<h3>{{ post.date }}</h3>
<p>{{ post.description|safe}}</p>
<img src="{{post.image.url }}" alt="{{ post.title }}" width="300" height="250">
<a href="javascript:history.back()">Volver atrás</a>
{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}

{% block content %}
<style>
    body {
        background: #090909;
    }

    .bg-black {
        background: #090909;
    }

    .card-project:hover {
        border: 1px solid #f9f9f9;
        cursor: pointer;
    }
    .card-project {
    display: flex; /* Utiliza flexbox para alinear los elementos */
    background-color: #f9f9f9;
    padding: 20px;
    margin-bottom: 20px;
}

.card-project img {
    max-width: 50%; /* Establece el ancho máximo de la imagen */
    height: auto; /* Mantiene la proporción de la imagen */
    margin-left: auto; /* Coloca la imagen en el lado derecho */
}

</style>

    <h1 style="color: white;">Post hechos de "blog" </h1> 
    {% for post in posts %}
        <div class="card mb-3 bg-black text-white">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid" style="max-height: 200px;">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h2 class="card-title">{{ post.title }}</h2>
                        <p class="card-text">{{ post.description | safe | truncatechars:100 }}</p>
                        <p class="card-text">{{ post.date|date:'M d Y'|upper }}</p>
                        <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary">Detalle</a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}
{% block content %}
{% load static %}
<header class="row">
  <div class="col-md-4">
    <img src="{% static 'cleo.jpeg' %}" alt="" width="200" height="200">
  </div>
  <div class="col-md-8">
    <h1>Ella es <strong>Cleo la gata mas hermosa</strong></h1>
    <h3>Guapisima</h3>
    <p>"Con su mirada tranquila y suavidad infinita, mi gato es el reflejo perfecto del amor en su forma más pura y serena."</p>
    <li class="nav-item d-flex align-items-center">
        <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'paraiso.pdf' %}">Download CV</a>
    </li>
  </div>
</header>

<header class="row"> <!-- Agregado -->
    <div class="col-md-8">
        <h1>Yo soy <strong>Mildreth Moreira</strong></h1>
        <h3>Como llego a mi Cleo?</h3>
        <p>En el mundo de los gatos callejeros, la historia de Cleo comienza como la de muchos otros: sin un hogar y luchando por sobrevivir en las duras calles de la ciudad. Abandonada por su antiguo dueño, esta pequeña gata tímida y solitaria vagaba por las calles, buscando refugio y comida donde pudiera encontrarla.

          Un día, el destino intervino y nuestros caminos se cruzaron. Me encontré con Cleo mientras caminaba por el vecindario. Sus ojos tristes y su pelaje desaliñado me rompieron el corazón, y supe en ese momento que tenía que hacer algo para ayudarla.
          
          Decidí llevarla a casa, aunque solo fuera temporalmente, para brindarle un lugar seguro y cálido donde pudiera recuperarse. Lo que comenzó como un acto de compasión pronto se convirtió en una profunda conexión. Cleo, con su naturaleza reservada pero dulce, rápidamente se ganó un lugar en mi corazón.
          
          A medida que pasaban los días, Cleo comenzó a florecer. Su pelaje se volvió más brillante, su paso más seguro y su confianza en sí misma creció día a día. Pero lo más importante, encontró algo que todos anhelamos: un hogar y una familia que la amaba incondicionalmente.
          
          Ahora, Cleo es la reina indiscutible de mi hogar. Sus ronroneos suaves y sus travesuras juguetonas llenan cada rincón con alegría y amor. Aunque su pasado puede haber sido difícil, ella nos enseña a todos sobre la resiliencia y la capacidad de encontrar la felicidad, sin importar las circunstancias.
          
          Cada vez que miro a Cleo, me recuerda el poder del amor y la importancia de brindar una segunda oportunidad. Ella puede haber sido abandonada una vez, pero ahora está rodeada de amor y cuidado, y eso es todo lo que importa.
          
          </p>
        <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'paraiso.pdf' %}" target="_blank">Download CV</a>
    </div>
</header> <!-- Cerrado -->
<!-- Porfolio Section -->
<div class="row my-4 text-center">

  <h3>BIBLIOTECA</h3>
  <p>Descubre con Cleo</p>

  {% for project in projects %}
  <div class="col-md-4 p-4">
    <div class="card bg-black card-project">
      <img src="{{project.image.url }}" class="card-img-top" />

      <div class="card-body">

        <h2>{{ project.title }}</h2>
        <p>{{ project.description }}</p>

        {% if project.url %}
        <a href="{{project.url}}" class="btn btn-light rounded-0 btn-sm" target="__blank" rel="noreferrer">Detallitos</a>
        {% endif %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>


{% endblock %}

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
     rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" 
     crossorigin="anonymous">
     <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">
    {% include 'partials/navbar.html' %}
    <div class="container p-4">
        {% block content %}
        {% endblock %}
    </div>
    <!-- Enlace al archivo JavaScript de Bootstrap (opcional) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-Lx6jpzqy/6GgLJLNxLBEwvD5xka09IebFYOZwqjrrjy1hzfJi0MIKv8SWhk9Ex0r" crossorigin="anonymous"></script>
</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand fw-bold fst-italic" href="/" style="color: white;">Mildreth Moreira</a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
                </li>
                <li class="nav-item d-flex align-items-center">
                    <a class="btn btn-primary btn-sm" href="{% static 'paraiso.pdf' %}" target="_blank">Download CV</a>
                </li>
            </ul>
        </div>
    </div>
</nav>